// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpODVoSRwSDJYH-qhpQcwTaSSnMccAvxU',
    appId: '1:314833789537:web:1dfa8b7c98d6d492310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    authDomain: 'bisonhacks-chatbot-3083e.firebaseapp.com',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    measurementId: 'G-BNT7PYZJQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPYB3wQF8Bui8G_UomVItSxqm-M4rlrk',
    appId: '1:314833789537:android:23d67b5f7cc79df1310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjGTZZMnP1AoUxn9TkLPuBiCC1Twu0T0',
    appId: '1:314833789537:ios:56bcb71844e77107310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSjGTZZMnP1AoUxn9TkLPuBiCC1Twu0T0',
    appId: '1:314833789537:ios:9ebbc777593f0adc310020',
    messagingSenderId: '314833789537',
    projectId: 'bisonhacks-chatbot-3083e',
    storageBucket: 'bisonhacks-chatbot-3083e.appspot.com',
    iosBundleId: 'com.example.chatbot.RunnerTests',
  );
}
